# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2023-02-18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest



class TestLinkError(unittest.TestCase):
    """LinkError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkError(self):
        """Test LinkError"""
        # inst = LinkError()


if __name__ == "__main__":
    unittest.main()
