# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.response401_get_user_links_users_id_links_get import (
    Response401GetUserLinksUsersIdLinksGet,
)


class TestResponse401GetUserLinksUsersIdLinksGet(unittest.TestCase):
    """Response401GetUserLinksUsersIdLinksGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Response401GetUserLinksUsersIdLinksGet:
        """Test Response401GetUserLinksUsersIdLinksGet
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Response401GetUserLinksUsersIdLinksGet`
        """
        model = Response401GetUserLinksUsersIdLinksGet()
        if include_optional:
            return Response401GetUserLinksUsersIdLinksGet(
                error_code = api_error.auth.unauthorized,
                error_message = Accounts access not permitted,
                documentation_url = None
            )
        else:
            return Response401GetUserLinksUsersIdLinksGet(
                error_message = Accounts access not permitted,
        )
        """

    def testResponse401GetUserLinksUsersIdLinksGet(self):
        """Test Response401GetUserLinksUsersIdLinksGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
