# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2023-02-18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.holding_response import HoldingResponse


class TestHoldingResponse(unittest.TestCase):
    """HoldingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HoldingResponse:
        """Test HoldingResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HoldingResponse`
        """
        model = HoldingResponse()
        if include_optional:
            return HoldingResponse(
                account_id = 'acc_6Tef269B6ZArSVpYrxtjBV',
                security_id = 'sec_bb6fi893jxdfNxyAjnb784',
                quantity = '10',
                price = '98.12',
                price_datetime = '2023-02-16T09:14:11',
                value = '987.15',
                cost_basis = '781.38'
            )
        else:
            return HoldingResponse(
                account_id = 'acc_6Tef269B6ZArSVpYrxtjBV',
                security_id = 'sec_bb6fi893jxdfNxyAjnb784',
                quantity = '10',
        )
        """

    def testHoldingResponse(self):
        """Test HoldingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
