# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.account_balances import AccountBalances


class TestAccountBalances(unittest.TestCase):
    """AccountBalances unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountBalances:
        """Test AccountBalances
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AccountBalances`
        """
        model = AccountBalances()
        if include_optional:
            return AccountBalances(
                currency = 'AFN',
                available = 340.12,
                current = 445.89,
                limit = 500
            )
        else:
            return AccountBalances(
                currency = 'AFN',
        )
        """

    def testAccountBalances(self):
        """Test AccountBalances"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
