# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.response401_get_account_numbers_links_id_accounts_numbers_get import (
    Response401GetAccountNumbersLinksIdAccountsNumbersGet,
)


class TestResponse401GetAccountNumbersLinksIdAccountsNumbersGet(unittest.TestCase):
    """Response401GetAccountNumbersLinksIdAccountsNumbersGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> Response401GetAccountNumbersLinksIdAccountsNumbersGet:
        """Test Response401GetAccountNumbersLinksIdAccountsNumbersGet
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Response401GetAccountNumbersLinksIdAccountsNumbersGet`
        """
        model = Response401GetAccountNumbersLinksIdAccountsNumbersGet()
        if include_optional:
            return Response401GetAccountNumbersLinksIdAccountsNumbersGet(
                error_code = link_error.unauthorized_access,
                error_message = None,
                documentation_url = None
            )
        else:
            return Response401GetAccountNumbersLinksIdAccountsNumbersGet(
                error_message = None,
        )
        """

    def testResponse401GetAccountNumbersLinksIdAccountsNumbersGet(self):
        """Test Response401GetAccountNumbersLinksIdAccountsNumbersGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
