# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.response401_get_user_transactions_users_id_transactions_get import (
    Response401GetUserTransactionsUsersIdTransactionsGet,
)


class TestResponse401GetUserTransactionsUsersIdTransactionsGet(unittest.TestCase):
    """Response401GetUserTransactionsUsersIdTransactionsGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> Response401GetUserTransactionsUsersIdTransactionsGet:
        """Test Response401GetUserTransactionsUsersIdTransactionsGet
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Response401GetUserTransactionsUsersIdTransactionsGet`
        """
        model = Response401GetUserTransactionsUsersIdTransactionsGet()
        if include_optional:
            return Response401GetUserTransactionsUsersIdTransactionsGet(
                error_code = api_error.auth.unauthorized,
                error_message = Accounts access not permitted,
                documentation_url = None
            )
        else:
            return Response401GetUserTransactionsUsersIdTransactionsGet(
                error_message = Accounts access not permitted,
        )
        """

    def testResponse401GetUserTransactionsUsersIdTransactionsGet(self):
        """Test Response401GetUserTransactionsUsersIdTransactionsGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
