# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.cursor_pagination import CursorPagination


class TestCursorPagination(unittest.TestCase):
    """CursorPagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CursorPagination:
        """Test CursorPagination
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CursorPagination`
        """
        model = CursorPagination()
        if include_optional:
            return CursorPagination(
                next = 'c2FtcGxlIGN1cnNvcg=='
            )
        else:
            return CursorPagination(
        )
        """

    def testCursorPagination(self):
        """Test CursorPagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
