# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.account_numbers import AccountNumbers


class TestAccountNumbers(unittest.TestCase):
    """AccountNumbers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountNumbers:
        """Test AccountNumbers
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AccountNumbers`
        """
        model = AccountNumbers()
        if include_optional:
            return AccountNumbers(
                ach = [
                    moneykit.models.ach_number.AchNumber(
                        account_number = '', 
                        routing_number = '', 
                        wire_routing_number = '', )
                    ],
                bacs = [
                    moneykit.models.bacs_number.BacsNumber(
                        account_number = '', 
                        sort_code = '', )
                    ],
                eft = [
                    moneykit.models.eft_number.EftNumber(
                        account_number = '', 
                        institution_number = '', 
                        branch_number = '', )
                    ],
                international = [
                    moneykit.models.international_number.InternationalNumber(
                        iban = '', 
                        bic = '', )
                    ]
            )
        else:
            return AccountNumbers(
                ach = [
                    moneykit.models.ach_number.AchNumber(
                        account_number = '', 
                        routing_number = '', 
                        wire_routing_number = '', )
                    ],
                bacs = [
                    moneykit.models.bacs_number.BacsNumber(
                        account_number = '', 
                        sort_code = '', )
                    ],
                eft = [
                    moneykit.models.eft_number.EftNumber(
                        account_number = '', 
                        institution_number = '', 
                        branch_number = '', )
                    ],
                international = [
                    moneykit.models.international_number.InternationalNumber(
                        iban = '', 
                        bic = '', )
                    ],
        )
        """

    def testAccountNumbers(self):
        """Test AccountNumbers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
