# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.customer_app import CustomerApp


class TestCustomerApp(unittest.TestCase):
    """CustomerApp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerApp:
        """Test CustomerApp
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CustomerApp`
        """
        model = CustomerApp()
        if include_optional:
            return CustomerApp(
                id = '3d18cdd1-fa96-4423-b781-bd5be036830e',
                app_name = 'My App'
            )
        else:
            return CustomerApp(
                id = '3d18cdd1-fa96-4423-b781-bd5be036830e',
                app_name = 'My App',
        )
        """

    def testCustomerApp(self):
        """Test CustomerApp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
