# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest


class TestWebhookLinkTestEvent(unittest.TestCase):
    """WebhookLinkTestEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookLinkTestEvent(self):
        """Test WebhookLinkTestEvent"""
        # inst = WebhookLinkTestEvent()


if __name__ == "__main__":
    unittest.main()
