# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.api.links_api import LinksApi


class TestLinksApi(unittest.TestCase):
    """LinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinksApi()

    def tearDown(self) -> None:
        pass

    def test_disconnect(self) -> None:
        """Test case for disconnect

        /links/{id}
        """
        pass

    def test_get_link(self) -> None:
        """Test case for get_link

        /links/{id}
        """
        pass

    def test_get_user_links(self) -> None:
        """Test case for get_user_links

        /users/{id}/links
        """
        pass

    def test_reset_login(self) -> None:
        """Test case for reset_login

        Force a \"relink required\" state on a link (Test only).
        """
        pass

    def test_update_link(self) -> None:
        """Test case for update_link

        /links/{id}
        """
        pass


if __name__ == "__main__":
    unittest.main()
