# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.link_product_refresh_webhook import LinkProductRefreshWebhook


class TestLinkProductRefreshWebhook(unittest.TestCase):
    """LinkProductRefreshWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkProductRefreshWebhook:
        """Test LinkProductRefreshWebhook
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LinkProductRefreshWebhook`
        """
        model = LinkProductRefreshWebhook()
        if include_optional:
            return LinkProductRefreshWebhook(
                webhook_event = 'link.product_refresh',
                webhook_major_version = 1,
                webhook_minor_version = 0,
                webhook_idempotency_key = '',
                webhook_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                link_id = '',
                link_tags = [
                    ''
                    ],
                product = 'accounts',
                state = 'completed',
                state_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error_message = ''
            )
        else:
            return LinkProductRefreshWebhook(
                webhook_idempotency_key = '',
                webhook_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                link_id = '',
                link_tags = [
                    ''
                    ],
                product = 'accounts',
                state = 'completed',
                state_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testLinkProductRefreshWebhook(self):
        """Test LinkProductRefreshWebhook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
