# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.account import Account


class TestAccount(unittest.TestCase):
    """Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Account:
        """Test Account
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Account`
        """
        model = Account()
        if include_optional:
            return Account(
                account_id = 'acc_6Tef269B6ZArSVpYrxtjBV',
                account_type = 'depository.checking',
                name = 'Premier Checking',
                account_mask = '3748',
                balances = moneykit.models.account_balances.AccountBalances(
                    currency = USD, 
                    available = 340.12, 
                    current = 445.89, 
                    limit = 500, )
            )
        else:
            return Account(
                account_id = 'acc_6Tef269B6ZArSVpYrxtjBV',
                account_type = 'depository.checking',
                name = 'Premier Checking',
                balances = moneykit.models.account_balances.AccountBalances(
                    currency = USD, 
                    available = 340.12, 
                    current = 445.89, 
                    limit = 500, ),
        )
        """

    def testAccount(self):
        """Test Account"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
