# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.introspect_client_response import IntrospectClientResponse


class TestIntrospectClientResponse(unittest.TestCase):
    """IntrospectClientResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntrospectClientResponse:
        """Test IntrospectClientResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IntrospectClientResponse`
        """
        model = IntrospectClientResponse()
        if include_optional:
            return IntrospectClientResponse(
                client_id = 'live_5c739a369515e10fc9e0',
                client_name = 'My App (Prod)',
                scope = '',
                app = moneykit.models.customer_app.CustomerApp(
                    id = '3d18cdd1-fa96-4423-b781-bd5be036830e', 
                    app_name = 'My App', ),
                disabled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return IntrospectClientResponse(
                client_id = 'live_5c739a369515e10fc9e0',
                client_name = 'My App (Prod)',
                scope = '',
                app = moneykit.models.customer_app.CustomerApp(
                    id = '3d18cdd1-fa96-4423-b781-bd5be036830e', 
                    app_name = 'My App', ),
        )
        """

    def testIntrospectClientResponse(self):
        """Test IntrospectClientResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
