# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.transaction_updates_available_webhook import (
    TransactionUpdatesAvailableWebhook,
)


class TestTransactionUpdatesAvailableWebhook(unittest.TestCase):
    """TransactionUpdatesAvailableWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionUpdatesAvailableWebhook:
        """Test TransactionUpdatesAvailableWebhook
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TransactionUpdatesAvailableWebhook`
        """
        model = TransactionUpdatesAvailableWebhook()
        if include_optional:
            return TransactionUpdatesAvailableWebhook(
                webhook_event = 'transactions.updates_available',
                webhook_major_version = 1,
                webhook_minor_version = 0,
                webhook_idempotency_key = '',
                webhook_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                link_id = '',
                has_history = True
            )
        else:
            return TransactionUpdatesAvailableWebhook(
                webhook_idempotency_key = '',
                webhook_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                link_id = '',
                has_history = True,
        )
        """

    def testTransactionUpdatesAvailableWebhook(self):
        """Test TransactionUpdatesAvailableWebhook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
