# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.link_session_customer_user_email import (
    LinkSessionCustomerUserEmail,
)


class TestLinkSessionCustomerUserEmail(unittest.TestCase):
    """LinkSessionCustomerUserEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkSessionCustomerUserEmail:
        """Test LinkSessionCustomerUserEmail
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LinkSessionCustomerUserEmail`
        """
        model = LinkSessionCustomerUserEmail()
        if include_optional:
            return LinkSessionCustomerUserEmail(
                address = 'k@>x u&K}qz^sEC(lJ)<,jQ*&5`$cClu+k& &su[-.zF5V+V5rEtCO>%17nxs\"k7z(!\\5\\$TMxo9,sWVoim8gs0123',
                customer_verified_at = '2023-02-16T00:00:00'
            )
        else:
            return LinkSessionCustomerUserEmail(
                address = 'k@>x u&K}qz^sEC(lJ)<,jQ*&5`$cClu+k& &su[-.zF5V+V5rEtCO>%17nxs\"k7z(!\\5\\$TMxo9,sWVoim8gs0123',
        )
        """

    def testLinkSessionCustomerUserEmail(self):
        """Test LinkSessionCustomerUserEmail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
