# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.identity_link_product import IdentityLinkProduct


class TestIdentityLinkProduct(unittest.TestCase):
    """IdentityLinkProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityLinkProduct:
        """Test IdentityLinkProduct
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IdentityLinkProduct`
        """
        model = IdentityLinkProduct()
        if include_optional:
            return IdentityLinkProduct(
                refreshed_at = '2023-02-16T09:14:11',
                last_attempted_at = '2023-02-16T09:14:11',
                settings = moneykit.models.identity_product_settings.IdentityProductSettings(
                    required = True, 
                    prefetch = True, 
                    product = null, )
            )
        else:
            return IdentityLinkProduct(
                settings = moneykit.models.identity_product_settings.IdentityProductSettings(
                    required = True, 
                    prefetch = True, 
                    product = null, ),
        )
        """

    def testIdentityLinkProduct(self):
        """Test IdentityLinkProduct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
