# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2023-02-18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.investment_transaction_response import (
    InvestmentTransactionResponse,
)


class TestInvestmentTransactionResponse(unittest.TestCase):
    """InvestmentTransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvestmentTransactionResponse:
        """Test InvestmentTransactionResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InvestmentTransactionResponse`
        """
        model = InvestmentTransactionResponse()
        if include_optional:
            return InvestmentTransactionResponse(
                id = 'it_R73abx78zoa2NxyAlki90g',
                account_id = 'acc_6Tef269B6ZArSVpYrxtjBV',
                amount = '987.15',
                var_date = '2023-02-16T00:00:00',
                datetime = '2023-02-16T09:14:11',
                description = 'Bought MSFT',
                type = 'buy',
                fees = '5.95',
                forex_rate = '',
                price = '98.12',
                quantity = '10',
                security_id = 'sec_bb6fi893jxdfNxyAjnb784'
            )
        else:
            return InvestmentTransactionResponse(
                id = 'it_R73abx78zoa2NxyAlki90g',
                account_id = 'acc_6Tef269B6ZArSVpYrxtjBV',
                amount = '987.15',
                var_date = '2023-02-16T00:00:00',
                description = 'Bought MSFT',
                type = 'buy',
        )
        """

    def testInvestmentTransactionResponse(self):
        """Test InvestmentTransactionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
