# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.link_session_customer_user_phone import (
    LinkSessionCustomerUserPhone,
)


class TestLinkSessionCustomerUserPhone(unittest.TestCase):
    """LinkSessionCustomerUserPhone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkSessionCustomerUserPhone:
        """Test LinkSessionCustomerUserPhone
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LinkSessionCustomerUserPhone`
        """
        model = LinkSessionCustomerUserPhone()
        if include_optional:
            return LinkSessionCustomerUserPhone(
                number = '+16175551212',
                country = 'US',
                customer_verified_at = '2023-02-16T00:00:00'
            )
        else:
            return LinkSessionCustomerUserPhone(
                number = '+16175551212',
        )
        """

    def testLinkSessionCustomerUserPhone(self):
        """Test LinkSessionCustomerUserPhone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
