# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest



class TestTransactionTypeFilter(unittest.TestCase):
    """TransactionTypeFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionTypeFilter(self):
        """Test TransactionTypeFilter"""
        # inst = TransactionTypeFilter()


if __name__ == "__main__":
    unittest.main()
