# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2023-02-18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.app_response import AppResponse


class TestAppResponse(unittest.TestCase):
    """AppResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppResponse:
        """Test AppResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AppResponse`
        """
        model = AppResponse()
        if include_optional:
            return AppResponse(
                app_id = '3d18cdd1-fa96-4423-b781-bd5be036830e',
                name = 'My App',
                id = '3d18cdd1-fa96-4423-b781-bd5be036830e',
                app_name = 'My App'
            )
        else:
            return AppResponse(
                app_id = '3d18cdd1-fa96-4423-b781-bd5be036830e',
                name = 'My App',
                id = '3d18cdd1-fa96-4423-b781-bd5be036830e',
                app_name = 'My App',
        )
        """

    def testAppResponse(self):
        """Test AppResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
