# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.requested_link_permission import RequestedLinkPermission


class TestRequestedLinkPermission(unittest.TestCase):
    """RequestedLinkPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestedLinkPermission:
        """Test RequestedLinkPermission
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RequestedLinkPermission`
        """
        model = RequestedLinkPermission()
        if include_optional:
            return RequestedLinkPermission(
                scope = 'accounts',
                reason = 'display your account balances',
                required = True
            )
        else:
            return RequestedLinkPermission(
                scope = 'accounts',
                reason = 'display your account balances',
                required = True,
        )
        """

    def testRequestedLinkPermission(self):
        """Test RequestedLinkPermission"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
