# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.link_session_error_forbidden_config_response import (
    LinkSessionErrorForbiddenConfigResponse,
)


class TestLinkSessionErrorForbiddenConfigResponse(unittest.TestCase):
    """LinkSessionErrorForbiddenConfigResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> LinkSessionErrorForbiddenConfigResponse:
        """Test LinkSessionErrorForbiddenConfigResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LinkSessionErrorForbiddenConfigResponse`
        """
        model = LinkSessionErrorForbiddenConfigResponse()
        if include_optional:
            return LinkSessionErrorForbiddenConfigResponse(
                error_code = 'link_session_error.forbidden_config',
                error_message = 'Forbidden use of a Connect feature',
                documentation_url = ''
            )
        else:
            return LinkSessionErrorForbiddenConfigResponse(
                error_message = 'Forbidden use of a Connect feature',
        )
        """

    def testLinkSessionErrorForbiddenConfigResponse(self):
        """Test LinkSessionErrorForbiddenConfigResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
