# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.basic_account_details import BasicAccountDetails


class TestBasicAccountDetails(unittest.TestCase):
    """BasicAccountDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BasicAccountDetails:
        """Test BasicAccountDetails
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BasicAccountDetails`
        """
        model = BasicAccountDetails()
        if include_optional:
            return BasicAccountDetails(
                name = 'Premier Checking',
                last_synced_at = '2023-02-16T09:14:11',
                institution_id = '',
                link_id = ''
            )
        else:
            return BasicAccountDetails(
                name = 'Premier Checking',
                institution_id = '',
                link_id = '',
        )
        """

    def testBasicAccountDetails(self):
        """Test BasicAccountDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
