# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.investments_product_settings import InvestmentsProductSettings


class TestInvestmentsProductSettings(unittest.TestCase):
    """InvestmentsProductSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvestmentsProductSettings:
        """Test InvestmentsProductSettings
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InvestmentsProductSettings`
        """
        model = InvestmentsProductSettings()
        if include_optional:
            return InvestmentsProductSettings(
                required = True,
                prefetch = True,
                product = 'accounts'
            )
        else:
            return InvestmentsProductSettings(
        )
        """

    def testInvestmentsProductSettings(self):
        """Test InvestmentsProductSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
