# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moneykit.models.generate_access_token_response import GenerateAccessTokenResponse


class TestGenerateAccessTokenResponse(unittest.TestCase):
    """GenerateAccessTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateAccessTokenResponse:
        """Test GenerateAccessTokenResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GenerateAccessTokenResponse`
        """
        model = GenerateAccessTokenResponse()
        if include_optional:
            return GenerateAccessTokenResponse(
                access_token = '52ea3d1b4f9a53fffb67...',
                token_type = 'bearer',
                expires_in = 3600
            )
        else:
            return GenerateAccessTokenResponse(
                access_token = '52ea3d1b4f9a53fffb67...',
                token_type = 'bearer',
                expires_in = 3600,
        )
        """

    def testGenerateAccessTokenResponse(self):
        """Test GenerateAccessTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
