# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.get_account_numbers_response_legacy20230218 import (
    GetAccountNumbersResponseLegacy20230218,
)


class TestGetAccountNumbersResponseLegacy20230218(unittest.TestCase):
    """GetAccountNumbersResponseLegacy20230218 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GetAccountNumbersResponseLegacy20230218:
        """Test GetAccountNumbersResponseLegacy20230218
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetAccountNumbersResponseLegacy20230218`
        """
        model = GetAccountNumbersResponseLegacy20230218()
        if include_optional:
            return GetAccountNumbersResponseLegacy20230218(
                accounts = [
                    moneykit.models.account_with_account_numbers_legacy_2023_02_18.AccountWithAccountNumbersLegacy_2023_02_18(
                        account_id = 'acc_6Tef269B6ZArSVpYrxtjBV', 
                        account_type = 'depository.checking', 
                        name = 'Premier Checking', 
                        account_mask = '3748', 
                        balances = null, 
                        numbers = null, )
                    ],
                link = {link_id=mk_eqkWN34UEoa2NxyALG8pcV, institution_id=chase, institution_name=Chase, institution_avatar=https://example.com/avatar.png, provider=mx, state=connected, last_synced_at=2023-02-16T09:14:11, tags=[user_type:admin], products={accounts={refreshed_at=2023-02-16T09:14:11, last_attempted_at=2023-02-16T09:14:11}, identity={refreshed_at=2023-02-16T09:14:11, last_attempted_at=2023-02-16T09:14:11, settings={required=true, prefetch=false}}}}
            )
        else:
            return GetAccountNumbersResponseLegacy20230218(
                accounts = [
                    moneykit.models.account_with_account_numbers_legacy_2023_02_18.AccountWithAccountNumbersLegacy_2023_02_18(
                        account_id = 'acc_6Tef269B6ZArSVpYrxtjBV', 
                        account_type = 'depository.checking', 
                        name = 'Premier Checking', 
                        account_mask = '3748', 
                        balances = null, 
                        numbers = null, )
                    ],
                link = {link_id=mk_eqkWN34UEoa2NxyALG8pcV, institution_id=chase, institution_name=Chase, institution_avatar=https://example.com/avatar.png, provider=mx, state=connected, last_synced_at=2023-02-16T09:14:11, tags=[user_type:admin], products={accounts={refreshed_at=2023-02-16T09:14:11, last_attempted_at=2023-02-16T09:14:11}, identity={refreshed_at=2023-02-16T09:14:11, last_attempted_at=2023-02-16T09:14:11, settings={required=true, prefetch=false}}}},
        )
        """

    def testGetAccountNumbersResponseLegacy20230218(self):
        """Test GetAccountNumbersResponseLegacy20230218"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
